export function downloadFile(
  content: string,
  filename: string,
  mimeType: string,
): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function copyToClipboard(text: string): Promise<void> {
  return navigator.clipboard.writeText(text);
}

export function exportAsJson(data: unknown, filename = "agentlint-report.json"): void {
  downloadFile(JSON.stringify(data, null, 2), filename, "application/json");
}

export function exportAsMarkdown(content: string, filename = "agentlint-report.md"): void {
  downloadFile(content, filename, "text/markdown");
}

export function exportAsHtml(content: string, title = "Agent Lint Report"): void {
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${escapeHtml(title)}</title>
<style>
  body { font-family: system-ui, -apple-system, sans-serif; max-width: 900px; margin: 0 auto; padding: 32px 24px; color: #0f172a; line-height: 1.6; }
  h1 { font-size: 1.5rem; border-bottom: 2px solid #e2e8f0; padding-bottom: 8px; }
  h2 { font-size: 1.25rem; margin-top: 32px; }
  h3 { font-size: 1rem; }
  pre { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 6px; padding: 16px; overflow-x: auto; font-size: 0.875rem; }
  code { font-family: "SF Mono", "Cascadia Code", Consolas, monospace; }
  table { border-collapse: collapse; width: 100%; margin: 16px 0; }
  th, td { text-align: left; padding: 8px 12px; border-bottom: 1px solid #e2e8f0; }
  th { font-weight: 600; font-size: 0.875rem; color: #475569; }
  .badge { display: inline-block; padding: 2px 8px; border-radius: 9999px; font-size: 0.75rem; font-weight: 600; }
  .error { background: #fee2e2; color: #dc2626; }
  .warning { background: #fef3c7; color: #d97706; }
  .success { background: #d1fae5; color: #059669; }
  .info { background: #dbeafe; color: #2563eb; }
  footer { margin-top: 48px; padding-top: 16px; border-top: 1px solid #e2e8f0; font-size: 0.8125rem; color: #94a3b8; }
</style>
</head>
<body>
${markdownToSimpleHtml(content)}
<footer>Generated by Agent Lint &mdash; ${new Date().toISOString().slice(0, 10)}</footer>
</body>
</html>`;
  downloadFile(html, "agentlint-report.html", "text/html");
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function markdownToSimpleHtml(md: string): string {
  return md
    .split("\n")
    .map((line) => {
      if (line.startsWith("### ")) return `<h3>${escapeHtml(line.slice(4))}</h3>`;
      if (line.startsWith("## ")) return `<h2>${escapeHtml(line.slice(3))}</h2>`;
      if (line.startsWith("# ")) return `<h1>${escapeHtml(line.slice(2))}</h1>`;
      if (line.startsWith("- ")) return `<li>${escapeHtml(line.slice(2))}</li>`;
      if (line.startsWith("```")) return "";
      if (line.trim() === "") return "<br/>";
      return `<p>${escapeHtml(line)}</p>`;
    })
    .join("\n");
}
